version: "3.6"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    restart: always
    networks:
      greece:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=gotoschool
      - DB_PASS=goto1234
      - DB_NAME=drachma

      - POSTGRES_DB=drachma
      - POSTGRES_DATABASE=drachma
      - POSTGRES_USER=gotoschool
      - POSTGRES_PASSWORD=goto1234
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
    restart:
      on-failure

  syracuse:
    image: gotoschool/syracuse:v0.0.1
    container_name: syracuse
    hostname: syracuse
    networks:
      greece:
        aliases:
          - syracuse
    environment:
      PORT: 8001
      POSTGRES_DSN: "postgres://gotoschool:goto1234@postgres:5432/drachma?sslmode=disable"
    depends_on:
      - postgres
    restart:
      on-failure

  sicily:
    image: gotoschool/sicily:v0.0.1
    container_name: sicily
    hostname: sicily
    networks:
      greece:
        aliases:
          - sicily
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CITIZENS_HOST: "syracuse"
      CITIZENS_PORT: 8001
      PALERMO_HOST: "palermo"
      PALERMO_PORT: 8003
    depends_on:
      - syracuse
      - palermo
    restart:
      on-failure

  palermo:
    image: gotoschool/palermo:v0.0.1
    container_name: palermo
    hostname: palermo
    networks:
      greece:
        aliases:
          - palermo
    environment:
      PORT: 8003
    restart:
      on-failure

networks:
  greece: {}
