apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gotoschool
spec:
  selector:
    matchLabels:
      run: gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway
        tier: backend
        version: v0.0.2
    spec:
      restartPolicy: Always
      containers:
      - name: sicily
        image: gotoschool/sicily:v0.0.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "3000"
        - name: CITIZENS_HOST
          value: $(SYRACUSE_SERVICE_HOST)
        - name: CITIZENS_PORT
          value: $(SYRACUSE_SERVICE_PORT)
        - name: PALERMO_HOST
          value: $(PALERMO_SERVICE_HOST)
        - name: PALERMO_PORT
          value: $(PALERMO_SERVICE_PORT)
        - name: PLATO_HOST
          value: $(PLATO_SERVICE_HOST)
        - name: PLATO_PORT
          value: $(PLATO_SERVICE_PORT)
        - name: HELENIA_HOST
          value: $(HELENIA_SERVICE_HOST)
        - name: HELENIA_PORT
          value: $(HELENIA_SERVICE_PORT)
        ports:
        - containerPort: 3000
          name: http-graphql
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-graphql
          initialDelaySeconds: 10
          timeoutSeconds: 1
        args:
        - -citizens-host=$(CITIZENS_HOST)
        - -citizens-port=$(CITIZENS_PORT)
        - -palermo-host=$(PALERMO_HOST)
        - -palermo-port=$(PALERMO_PORT)
        - -plato-host=$(PLATO_HOST)
        - -plato-port=$(PLATO_PORT)
        - -helenia-host=$(HELENIA_HOST)
        - -helenia-port=$(HELENIA_PORT)
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: gotoschool
  labels:
    run: gateway
    tier: backend
spec:
  ports:
  - name: http-graphql
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: gateway
    tier: backend