apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: http
  selector:
    app: gateway
    tier: frontend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        tier: frontend
        release: stable
    spec:
      restartPolicy: Always
      containers:
      - name: sicily
        image: gotoschool/sicily:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "3000"
        - name: CITIZENS_HOST
          value: $(SYRACUSE_SERVICE_HOST)
        - name: CITIZENS_PORT
          value: "8001"
        - name: PALERMO_HOST
          value: $(PALERMO_SERVICE_HOST)
        - name: PALERMO_PORT
          value: "8003"
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 1