apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      run: gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway
        tier: backend
        version: v0.0.2
    spec:
      restartPolicy: Always
      containers:
      - name: sicily
        image: gotoschool/sicily:v0.0.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: PORT
          value: "3000"
        - name: CITIZENS_HOST
          value: $(SYRACUSE_SERVICE_HOST)
        - name: CITIZENS_PORT
          value: "8001"
        - name: PALERMO_HOST
          value: $(PALERMO_SERVICE_HOST)
        - name: PALERMO_PORT
          value: "8003"
        ports:
        - containerPort: 3000
          name: http-graphql
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-graphql
          initialDelaySeconds: 10
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-svc
  labels:
    run: gateway
    tier: backend
spec:
  ports:
  - name: http-graphql
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: gateway
    tier: backend