apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gotoschool
  name: helenia
spec:
  selector:
    matchLabels:
      run: helenia
  replicas: 1
  template:
    metadata:
      labels:
        run: helenia
        tier: backend
        version: v0.0.1
    spec:
      restartPolicy: Always
      containers:
      - name: helenia
        image: gotoschool/helenia:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POSTGRES_DSN
          value: "postgres://gotoschool:goto1234@$(POSTGRES_SERVICE_HOST):$(POSTGRES_SERVICE_PORT)/drachma?sslmode=disable"
        ports:
        - containerPort: 8005
          name: grpc-port-05
        args:
        - -postgres-dsn=$(POSTGRES_DSN)
---
apiVersion: v1
kind: Service
metadata:
  namespace: gotoschool
  name: helenia
  labels:
    run: helenia
    tier: backend
spec:
  ports:
  - name: grpc-port-05
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    run: helenia
    tier: backend