apiVersion: v1
kind: LimitRange
metadata:
  namespace: gotoschool
  name: limits
spec:
  limits:
  - type: Container
    default:
      memory: 128Mi
      cpu: 200m
    defaultRequest:
      memory: 64Mi
      cpu: 100m
  - type: Pod
    max:
      memory: 256Mi
    min:
      memory: 128Mi
