apiVersion: v1
kind: Service
metadata:
  name: palermo
  namespace: gotoschool
  labels:
    run: palermo
    tier: backend
spec:
  ports:
  - port: 8003
    targetPort: grpc-port-03
  selector:
    run: palermo
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: palermo
  namespace: gotoschool
  labels:
    run: palermo
spec:
  selector:
    matchLabels:
      run: palermo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: palermo
        tier: backend
        version: v0.0.1
    spec:
      containers:
      - name: master
        image: docker.io/gotoschool/palermo:v0.0.1
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8003
          name: grpc-port-03