apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gotoschool
  name: plato
spec:
  selector:
    matchLabels:
      run: plato
  replicas: 1
  template:
    metadata:
      labels:
        run: plato
        tier: backend
        version: v0.0.1
    spec:
      restartPolicy: Always
      containers:
      - name: plato
        image: gotoschool/plato:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POSTGRES_DSN
          value: "postgres://gotoschool:goto1234@$(POSTGRES_SERVICE_HOST):$(POSTGRES_SERVICE_PORT)/drachma?sslmode=disable"
        ports:
        - containerPort: 8004
          name: grpc-port-04
        args:
        - -postgres-dsn=$(POSTGRES_DSN)
---
apiVersion: v1
kind: Service
metadata:
  namespace: gotoschool
  name: plato
  labels:
    run: plato
    tier: backend
spec:
  ports:
  - name: grpc-port-04
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    run: plato
    tier: backend