apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
  namespace: gotoschool
spec:
  selector:
    matchLabels:
      run: session
  replicas: 1
  template:
    metadata:
      labels:
        run: session
        tier: backend
        version: v0.0.1
    spec:
      restartPolicy: Always
      containers:
      - name: session
        image: gotoschool/atenea:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "3001"
        - name: CITIZENS_HOST
          value: $(SYRACUSE_SERVICE_HOST)
        - name: CITIZENS_PORT
          value: "8001"
        - name: PALERMO_HOST
          value: $(PALERMO_SERVICE_HOST)
        - name: PALERMO_PORT
          value: "8003"
        ports:
        - containerPort: 3001
          name: http-session
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-session
          initialDelaySeconds: 10
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: session
  namespace: gotoschool
  labels:
    run: session
    tier: backend
spec:
  ports:
  - name: http-session
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    run: session
    tier: backend