apiVersion: v1
kind: Service
metadata:
  name: syracuse
  labels:
    app: syracuse
    role: master
    tier: backend
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: syracuse
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syracuse
spec:
  selector:
    matchLabels:
      app: syracuse
      role: master
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: syracuse
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: docker.io/gotoschool/syracuse:v0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: POSTGRES_DSN
          value: "postgres://gotoschool:goto1234@$(POSTGRES_SERVICE_HOST):5432/greek?sslmode=disable"