apiVersion: v1
kind: Service
metadata:
  name: syracuse
  labels:
    run: syracuse
    tier: backend
spec:
  ports:
  - port: 8001
    targetPort: grpc-port-01
  selector:
    run: syracuse
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syracuse
  labels:
    run: syracuse
spec:
  selector:
    matchLabels:
      run: syracuse
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        run: syracuse
        uses: postgres
        tier: backend
        version: v0.0.1
    spec:
      containers:
      - name: master
        image: docker.io/gotoschool/syracuse:v0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8001
          name: grpc-port-01
        env:
        - name: PORT
          value: "8001"
        - name: POSTGRES_DSN
          value: "postgres://gotoschool:goto1234@$(POSTGRES_SERVICE_HOST):5432/greek?sslmode=disable"